### ISSUE TITLE
org.frice.designer.Main 没这个类啊

### ISSUE THREAD

**Issue by luckyCatMiao** [icela/FriceDesigner#2]
org.frice.designer.Main 没这个类啊 你build文件是不是有点问题

**Comment by ice1000** [comment]
我看看

**Comment by ice1000** [comment]
我检查了一下。之前的做法实际上是使用了resources里面的META-INF文件，which is 正确的，因此build.gradle里面的被替换掉了。现在没有这个问题了，我还顺手修复了一些与依赖有关的问题和整理代码风格。谢谢反馈。

**Comment by luckyCatMiao** [comment]
。。fxml文件是不是没有打包到jar里

**Comment by ice1000** [comment]
是的。。。谢特
